import javax.swing.JOptionPane;

/**
 *
 * @author AndresR
 */
public class JframeP3 extends javax.swing.JFrame {

    /**
     * Creates new form JframeP3
     */
    public JframeP3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        txtMay = new javax.swing.JTextField();
        txtMed = new javax.swing.JTextField();
        txtMen = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblN1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        lblMay = new javax.swing.JLabel();
        lblMed = new javax.swing.JLabel();
        lblMen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Comparar Números");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 590, 20));
        getContentPane().add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, -1));
        getContentPane().add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, -1));
        getContentPane().add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 70, -1));
        getContentPane().add(txtMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 70, -1));
        getContentPane().add(txtMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 70, -1));
        getContentPane().add(txtMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 70, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        lblN1.setText("Número1:");
        getContentPane().add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblN2.setText("Número2:");
        getContentPane().add(lblN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblN3.setText("Número3:");
        getContentPane().add(lblN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        lblMay.setText("Mayor:");
        getContentPane().add(lblMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        lblMed.setText("Medio:");
        getContentPane().add(lblMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        lblMen.setText("Menor:");
        getContentPane().add(lblMen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
        txtN1.setText("");
        txtN2.setText("");
        txtN3.setText("");
        
        txtMay.setText("");
        txtMed.setText("");
        txtMen.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int i=JOptionPane.showConfirmDialog(rootPane, "Esta apunto de salir, ¿desea continuar?");
        if(i==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try{
            double n1,n2,n3,may,men,med;
            n1=Double.parseDouble(txtN1.getText());
            n2=Double.parseDouble(txtN2.getText());
            n3=Double.parseDouble(txtN3.getText());
            may=n1;
            if(may<n2){may=n2;}
            if(may<n3){may=n3;}
            men=n1;
            if(men>n2){men=n2;}
            if(men>n3){men=n3;}
            //medio
            med=0;
            if(n1!=may && n1!=men){med=n1;}
            if(n2!=may && n2!=men){med=n2;}
            if(n3!=may && n3!=men){med=n3;}
            
            txtMay.setText(String.valueOf(may));
            txtMed.setText(String.valueOf(med));
            txtMen.setText(String.valueOf(men));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ingrese los datos correctos");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMay;
    private javax.swing.JLabel lblMed;
    private javax.swing.JLabel lblMen;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtMay;
    private javax.swing.JTextField txtMed;
    private javax.swing.JTextField txtMen;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    // End of variables declaration//GEN-END:variables
}
