/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase04;

import javax.swing.JOptionPane;

/**
 *
 * @author AndresR
 */
public class JframeP1 extends javax.swing.JFrame {

    /**
     * Creates new form JframeP1
     */
    public JframeP1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalcular = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblN1 = new javax.swing.JLabel();
        lblN2 = new javax.swing.JLabel();
        lblN3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtN4 = new javax.swing.JTextField();
        lblN5 = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        lblPromedio = new javax.swing.JLabel();
        txtVentaMayor = new javax.swing.JTextField();
        lblVentaMayor = new javax.swing.JLabel();
        txtVentaMenor = new javax.swing.JTextField();
        lblVentaMenor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 280, -1));

        txtN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 280, -1));

        txtN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 280, -1));

        txtTotal.setEditable(false);
        txtTotal.setFocusable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 70, -1));

        txtN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Calcular Ventas");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        lblName.setText("Nombre:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblN1.setText("Venta1:");
        getContentPane().add(lblN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblN2.setText("Venta2:");
        getContentPane().add(lblN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lblN3.setText("Venta3:");
        getContentPane().add(lblN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 720, 20));

        txtN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtN4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 280, -1));

        lblN5.setText("Venta4:");
        getContentPane().add(lblN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txtPromedio.setEditable(false);
        txtPromedio.setFocusable(false);
        txtPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, -1));

        lblPromedio.setText("Promedio:");
        getContentPane().add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        txtVentaMayor.setEditable(false);
        txtVentaMayor.setFocusable(false);
        txtVentaMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaMayorActionPerformed(evt);
            }
        });
        getContentPane().add(txtVentaMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, -1));

        lblVentaMayor.setText("Venta Mayor:");
        getContentPane().add(lblVentaMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        txtVentaMenor.setEditable(false);
        txtVentaMenor.setFocusable(false);
        txtVentaMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVentaMenorActionPerformed(evt);
            }
        });
        getContentPane().add(txtVentaMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 70, -1));

        lblVentaMenor.setText("Venta Menor:");
        getContentPane().add(lblVentaMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /*
        Ejercicio 1:
        Crear un programa que permita ingresar el nombre del vendedor 
        y sus cuatro ventas realizadas, realizar las operaciones 
        correspondientes para obtener los siguientes resultados. 
        Visualizar el total, promedio, venta mayor  y menor.

        */
        try{
        //declarar variables
        String name="";
        double v1,v2,v3,v4;
        double prom,total,ventaMay,ventaMen;
        name=txtName.getText();
        //ingresa datos
        v1=Double.parseDouble(txtN1.getText());
        v2=Double.parseDouble(txtN2.getText());
        v3=Double.parseDouble(txtN3.getText());
        v4=Double.parseDouble(txtN4.getText());
        total=v1+v2+v3+v4;
        prom=total/4;
        ventaMay=v1;
            if (v2>ventaMay) {ventaMay=v2;}
            if (v3>ventaMay) {ventaMay=v3;}
            if (v4>ventaMay) {ventaMay=v4;}
        ventaMen=v1;
            if (v2<ventaMen) {ventaMen=v2;}
            if (v3<ventaMen) {ventaMen=v3;}
            if (v4<ventaMen) {ventaMen=v4;}
        txtTotal.setText(String.valueOf(total));
        txtPromedio.setText(String.valueOf(prom));
        txtVentaMayor.setText(String.valueOf(ventaMay));
        txtVentaMenor.setText(String.valueOf(ventaMen));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ingrese los datos correctamente", "Error Encontrado", HEIGHT);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN2ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN3ActionPerformed

    private void txtN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN4ActionPerformed

    private void txtPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedioActionPerformed

    private void txtVentaMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaMayorActionPerformed

    private void txtVentaMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVentaMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVentaMenorActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtName.setText("");
        txtN1.setText("");
        txtN2.setText("");
        txtN3.setText("");
        txtN4.setText("");
        txtPromedio.setText("");
        txtTotal.setText("");
        txtVentaMayor.setText("");
        txtVentaMenor.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       int i=JOptionPane.showConfirmDialog(rootPane, "Esta apunto de salir, ¿desea continuar?");
       if(i==0){
           System.exit(0);
       }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblN2;
    private javax.swing.JLabel lblN3;
    private javax.swing.JLabel lblN5;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVentaMayor;
    private javax.swing.JLabel lblVentaMenor;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtN4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVentaMayor;
    private javax.swing.JTextField txtVentaMenor;
    // End of variables declaration//GEN-END:variables
}
