/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase04;

import javax.swing.JOptionPane;

/**
 *
 * @author AndresR
 */
public class JframeP2 extends javax.swing.JFrame {

    /**
     * Creates new form JframeP2
     */
    public JframeP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblBono1 = new javax.swing.JLabel();
        txtBono1 = new javax.swing.JTextField();
        lblBono2 = new javax.swing.JLabel();
        txtBono2 = new javax.swing.JTextField();
        lblBono3 = new javax.swing.JLabel();
        txtBono3 = new javax.swing.JTextField();
        txtBono4 = new javax.swing.JTextField();
        lblBono4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        txtBMayor = new javax.swing.JTextField();
        lblVentaMayor = new javax.swing.JLabel();
        lblVentaMenor = new javax.swing.JLabel();
        txtBMenor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 30, 40));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Calcular Bonos");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        lblName.setText("Nombre:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, -1));

        lblBono1.setText("Bono1");
        getContentPane().add(lblBono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        txtBono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBono1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        lblBono2.setText("Bono2");
        getContentPane().add(lblBono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        txtBono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBono2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, -1));

        lblBono3.setText("Bono3");
        getContentPane().add(lblBono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        txtBono3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBono3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 70, -1));

        txtBono4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBono4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtBono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 70, -1));

        lblBono4.setText("Bono4");
        getContentPane().add(lblBono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setFocusable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 70, -1));

        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        lblPromedio.setText("Promedio:");
        getContentPane().add(lblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        txtPromedio.setEditable(false);
        txtPromedio.setFocusable(false);
        txtPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromedioActionPerformed(evt);
            }
        });
        getContentPane().add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 70, -1));

        txtBMayor.setEditable(false);
        txtBMayor.setFocusable(false);
        txtBMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBMayorActionPerformed(evt);
            }
        });
        getContentPane().add(txtBMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 70, -1));

        lblVentaMayor.setText("Bono Mayor:");
        getContentPane().add(lblVentaMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        lblVentaMenor.setText("Bono Menor:");
        getContentPane().add(lblVentaMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        txtBMenor.setEditable(false);
        txtBMenor.setFocusable(false);
        txtBMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBMenorActionPerformed(evt);
            }
        });
        getContentPane().add(txtBMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 70, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 20));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /*
        Crear un programa que permita ingresar el nombre del empleado 
        y sus cuatro bonos obtenidos, realizar las operaciones 
        correspondientes para obtener los siguientes resultados. 
        Visualizar el total, promedio y los bonos mayor y menor valor.
        */
        try{
        //declarar variables
        String name="";
        double v1,v2,v3,v4;
        double prom,total,ventaMay,ventaMen;
        name=txtName.getText();
        //ingresa datos
        v1=Double.parseDouble(txtBono1.getText());
        v2=Double.parseDouble(txtBono2.getText());
        v3=Double.parseDouble(txtBono3.getText());
        v4=Double.parseDouble(txtBono4.getText());
        total=v1+v2+v3+v4;
        prom=total/4;
        ventaMay=v1;
            if (v2>ventaMay) {ventaMay=v2;}
            if (v3>ventaMay) {ventaMay=v3;}
            if (v4>ventaMay) {ventaMay=v4;}
        ventaMen=v1;
            if (v2<ventaMen) {ventaMen=v2;}
            if (v3<ventaMen) {ventaMen=v3;}
            if (v4<ventaMen) {ventaMen=v4;}
        txtTotal.setText(String.valueOf(total));
        txtPromedio.setText(String.valueOf(prom));
        txtBMayor.setText(String.valueOf(ventaMay));
        txtBMenor.setText(String.valueOf(ventaMen));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ingrese los datos correctamente", "Error Encontrado", HEIGHT);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBono1ActionPerformed

    private void txtBono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBono2ActionPerformed

    private void txtBono3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBono3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBono3ActionPerformed

    private void txtBono4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBono4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBono4ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromedioActionPerformed

    private void txtBMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBMayorActionPerformed

    private void txtBMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBMenorActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtName.setText("");
        txtBono1.setText("");
        txtBono2.setText("");
        txtBono3.setText("");
        txtBono4.setText("");
        txtPromedio.setText("");
        txtTotal.setText("");
        txtBMayor.setText("");
        txtBMenor.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int i=JOptionPane.showConfirmDialog(rootPane, "Esta apunto de salir, ¿desea continuar?");
        if(i==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBono1;
    private javax.swing.JLabel lblBono2;
    private javax.swing.JLabel lblBono3;
    private javax.swing.JLabel lblBono4;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVentaMayor;
    private javax.swing.JLabel lblVentaMenor;
    private javax.swing.JTextField txtBMayor;
    private javax.swing.JTextField txtBMenor;
    private javax.swing.JTextField txtBono1;
    private javax.swing.JTextField txtBono2;
    private javax.swing.JTextField txtBono3;
    private javax.swing.JTextField txtBono4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
