package vista;

import modelo.SueldoEmpleadoClass;

public class SueldoEmpleadoForm extends javax.swing.JFrame {

    public SueldoEmpleadoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSueldo5 = new javax.swing.JTextField();
        txtSueldo1 = new javax.swing.JTextField();
        txtSueldo2 = new javax.swing.JTextField();
        txtSueldo3 = new javax.swing.JTextField();
        txtSueldo4 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMenor = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtPromedio = new javax.swing.JTextField();
        txtMayor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sueldo de empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setText("Sueldo 5:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setText("Sueldo 1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("Sueldo 2:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setText("Sueldo 3:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel6.setText("Sueldo 4:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        getContentPane().add(txtSueldo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, -1));
        getContentPane().add(txtSueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, -1));
        getContentPane().add(txtSueldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 100, -1));
        getContentPane().add(txtSueldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, -1));
        getContentPane().add(txtSueldo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Promedio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Menor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Mayor");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));
        getContentPane().add(txtMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 70, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, -1));
        getContentPane().add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 70, -1));
        getContentPane().add(txtMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double sueldo1,sueldo2,sueldo3,sueldo4,sueldo5;
        
        sueldo1=Double.parseDouble(txtSueldo1.getText());
        sueldo2=Double.parseDouble(txtSueldo2.getText());
        sueldo3=Double.parseDouble(txtSueldo3.getText());
        sueldo4=Double.parseDouble(txtSueldo4.getText());
        sueldo5=Double.parseDouble(txtSueldo5.getText());
        
        SueldoEmpleadoClass empleadoForm = new SueldoEmpleadoClass();
        
        empleadoForm.setSueldo1(sueldo1);
        empleadoForm.setSueldo2(sueldo2);
        empleadoForm.setSueldo3(sueldo3);
        empleadoForm.setSueldo4(sueldo4);
        empleadoForm.setSueldo5(sueldo5);
        
        txtTotal.setText(String.valueOf(empleadoForm.total()));
        txtPromedio.setText(String.valueOf(empleadoForm.promedio()));
        txtMayor.setText(String.valueOf(empleadoForm.mayor()));
        txtMenor.setText(String.valueOf(empleadoForm.menor()));
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SueldoEmpleadoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SueldoEmpleadoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtMayor;
    private javax.swing.JTextField txtMenor;
    private javax.swing.JTextField txtPromedio;
    private javax.swing.JTextField txtSueldo1;
    private javax.swing.JTextField txtSueldo2;
    private javax.swing.JTextField txtSueldo3;
    private javax.swing.JTextField txtSueldo4;
    private javax.swing.JTextField txtSueldo5;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
